# Generated by Django 4.0.1 on 2022-05-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniprof', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprof',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
