# Generated by Django 4.0.5 on 2022-06-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniprof', '0003_alter_alumniprof_city_alter_alumniprof_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprof',
            name='hs_activities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
