# Generated by Django 4.0.5 on 2022-06-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniprof', '0004_alter_alumniprof_hs_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprof',
            name='interview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alumniprof',
            name='newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
