# Generated by Django 4.0.5 on 2022-06-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniprof', '0005_alumniprof_interview_alumniprof_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprof',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='alumniprof',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
