# Generated by Django 4.0.5 on 2022-06-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniprof', '0006_alter_alumniprof_state_alter_alumniprof_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprof',
            name='relation',
            field=models.CharField(default='Student (Current/Former)', max_length=100),
            preserve_default=False,
        ),
    ]
