# Generated by Django 4.0.5 on 2022-06-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumniprof', '0007_alumniprof_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprof',
            name='field',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='alumniprof',
            name='hs_activities',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
